### ISSUE TITLE
Suggestions for Moq are not working on Visual Studio 2019

### ISSUE THREAD

**Issue by cezarypiatek** [MrLuje/Mocking.Helpers#8]
Hi,

I've tried to use `Mocking.Helpers` on Visual Studio 2019 (16.1.6) but it doesn't work.

![image](https://user-images.githubusercontent.com/7759991/61652978-80b84d00-acb9-11e9-8ece-2d756579cd68.png)

On Visual Studio 2017 it works like a charm.

**Comment by MrLuje** [comment]
Can you confirm if you are using R# or not ?
Mocking.Helpers hooks into Vs Intellisense, not Resharper's

**Comment by cezarypiatek** [comment]
Yes, I'm using VS with R#.

It looks like the same issue as here https://github.com/Litee/moq.autocomplete/issues/1
Your  plugin is using the same logic to find `tokenAtCursor`

**Comment by MrLuje** [comment]
If you are using R# Intellisense, this extension can't hook into it. You will need a R# extension for that.

![image](https://user-images.githubusercontent.com/632075/62448624-92452e80-b768-11e9-8f71-5abbc6c41300.png)

As you mentioned in https://github.com/Litee/moq.autocomplete/issues/1, CTRL+J works because VS Intellisense handles it, not R# (which is a good workaround I didn't know about, btw 😃)

**Comment by cezarypiatek** [comment]
@MrLuje thanks for the explanation, I wasn't aware of these settings in R#.
